### ISSUE TITLE
[Question]: Is ARM arch supported?

### ISSUE THREAD

**Issue by gabeklavans** [dockur/macos#103]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/macos/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

I tried running in my M1 mac-mini but it was so slow I couldn't even configure the VM. My guess is because it's emulating x86, but I just wanted to check for sure.

**Comment by gabeklavans** [comment]
Thanks! Are there any plans for an arm version of this repo, like with windows-arm?

**Comment by JaneX8** [comment]
> Thanks! Are there any plans for an arm version of this repo, like with windows-arm?

I would like to know this too.

**Comment by i-rocky** [comment]
@kroese is it possible to run arm64 variant of macOS on arm64 host? 
Does it slow down as well?
