### ISSUE TITLE
[Bug]: ERROR: Failed to fetch macOS "13" recovery image with board id "Mac-4B682C642B45593E"!

### ISSUE THREAD

**Issue by lzfgit-byte** [dockur/macos#112]
### Operating system

Ubuntu 22.04.3 LTS (Jammy Jellyfish)

### Description

ERROR: Failed to fetch macOS "13" recovery image with board id "Mac-4B682C642B45593E"!

### Docker compose

services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m

### Docker log

❯ Starting macOS for Docker v1.15...
❯ For support visit https://github.com/dockur/macos
❯ CPU: 13th Gen Intel Core TM i5 13500H | RAM: 9/16 GB | DISK: 868 GB (ext4) | HOST: 5.15.153.1-microsoft-standard-WSL2...

❯ Downloading macOS 13 recovery image...
ERROR: "HTTP Error 403: " when connecting to http://osrecovery.apple.com/InstallationPayload/RecoveryImage
❯ ERROR: Failed to fetch macOS "13" recovery image with board id "Mac-4B682C642B45593E"!

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/495f89db-fdcd-42b6-a335-c8a5a0089a6d)

**Comment by DaRandomCube** [comment]
it's not about firewall, i cannot access that link too, it just shows blank page

**Comment by Bhargav0405** [comment]
try using VPN

**Comment by lzfgit-byte** [comment]
solved with vpn.Thanks guys

**Comment by Leaderzhangyi** [comment]
挂了vpn也没有解决

**Comment by lzfgit-byte** [comment]
> 挂了vpn也没有解决

vpn质量不行
