### ISSUE TITLE
当我安装macos时，提示没有连接网络

### ISSUE THREAD

**Issue by virkingz** [dockur/macos#171]
### Operating system

ubuntu:16.04

### Description

当我安装macos时，提示没有连接网络

### Docker compose

version: '3.8'
services:
  macos:
    image: dockurr/macos
    container_name: macos     #   容器名称
    environment:
      VERSION: "13"
    privileged: true
    volumes:
      - ./osx:/storage   #  磁盘映射的本地路径，我在Portainer中讲到过
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 8006:8006
      - "5900:5900/tcp"
      - "5900:5900/udp"
    stop_grace_period: 2m

### Docker log

![image](https://github.com/user-attachments/assets/d235f860-ba6b-414b-8b47-e9ee2b9752ed)

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/d063991e-0474-4d2b-89c9-fd54f023a0a1)

**Comment by puteulanus** [comment]
I am experiencing the same issue, with symptoms identical to this comment: https://github.com/dockur/macos/issues/173#issuecomment-2562352026.

After manually configuring the network interface in the VM with the correct IP address, subnet mask, and gateway, I was able to ping 20.20.20.1 and ping 8.8.8.8 successfully. This indicates that basic network connectivity is working, and the problem seems to lie with the DHCP service.

To investigate further, I manually started dnsmasq with the following command:

/usr/sbin/dnsmasq --dhcp-range=20.20.20.21,20.20.20.21 --dhcp-host=00:16:CB:94:A1:60,,20.20.20.21,QEMU,infinite --dhcp-option=option:netmask,255.255.255.0 --dhcp-option=option:dns-server,20.20.20.1 --dhcp-option=option:router,20.20.20.1 --address=/host.lan/20.20.20.1 -d

This produced the following logs:

```
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPDISCOVER(dockerbridge) 00:16:cb:94:a1:60
dnsmasq-dhcp: DHCPOFFER(dockerbridge) 20.20.20.21 00:16:cb:94:a1:60
```

Despite this, the VM still ends up with a 169.x.x.x address: 
![QQ_1735235202230](https://github.com/user-attachments/assets/55a8b406-a8aa-4349-bb6e-32433b86e7dc)

**Comment by virkingz** [comment]
@puteulanus 
after using your method, I can also continue with the installation!

**Comment by virkingz** [comment]
@puteulanus 
When I install the system, it prompts an error occurred preparing the software update。 Have you encountered this problem？

**Comment by puteulanus** [comment]
> @puteulanus When I install the system, it prompts an error occurred preparing the software update。 Have you encountered this problem？

No, I didn't encounter it, but during system initialization after the installation, DHCP still doesn't seem to work properly.

![QQ_1735272703740](https://github.com/user-attachments/assets/ee661a65-1241-4cb3-bad6-ea8124b6b690)

![QQ_1735273275642](https://github.com/user-attachments/assets/9b1d43dd-6976-4630-8c2b-60051eb11eed)

**Comment by ncheng89** [comment]
![image](https://github.com/user-attachments/assets/0b428bc9-4a7b-4a7d-bbbc-de8c449b1560)
But the DNS still does not work, there is no problem with the gateway

**Comment by virkingz** [comment]
> > @puteulanus我在安装系统的时候提示准备软件更新时出错。你有遇到过这个问题吗？
> 
> 没有，我没有遇到过，但是在安装后的系统初始化过程中，DHCP似乎仍然无法正常工作。
> 
> ![QQ_1735272703740](https://private-user-images.githubusercontent.com/4849177/398845864-ee661a65-1241-4cb3-bad6-ea8124b6b690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODM3ODAsIm5iZiI6MTczNTI4MzQ4MCwicGF0aCI6Ii80ODQ5MTc3LzM5ODg0NTg2NC1lZTY2MWE2NS0xMjQxLTRjYjMtYmFkNi1lYTgxMjRiNmI2OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjdUMDcxMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JhMjc5NWI0NDU4MjVhNzM2ZTQ3ZDM2YTRkN2VkOTU4Y2VmZTJjZGJjMzk1NGMyOGZhZDZlZmJmYjVhOWUxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QZF0L8XHlgzSDarNxLJWbnAGBLF3rP_vO54q01-sXBg)
> 
> ![QQ_1735273275642](https://private-user-images.githubusercontent.com/4849177/398845876-9b1d43dd-6976-4630-8c2b-60051eb11eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODM3ODAsIm5iZiI6MTczNTI4MzQ4MCwicGF0aCI6Ii80ODQ5MTc3LzM5ODg0NTg3Ni05YjFkNDNkZC02OTc2LTQ2MzAtOGMyYi02MDA1MWViMTFlZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjdUMDcxMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njc4NjI2ZDFkMmNjNGExZjEwMjhkMDQ3MWE5YTAyYWJlNzIzMGIxNTkyMGYxY2U1NzIzMzRlMTliZjkzMTQ3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.n3RDmFpJg_8XXii0-rz63CtTuqQt4by9Y23OgH05UAk)

Do you know how to solve it  https://github.com/dockur/macos/issues/93#issuecomment-2563287467

**Comment by puteulanus** [comment]
> But the DNS still does not work, there is no problem with the gateway

Yes, I did encounter this issue. It feels like a DNS service needs to be restarted, but I don't know how to do that in recovery mode. After writing to `/etc/resolv.conf`, both `ping` and `curl` fail to resolve immediately. 

What I did was close the terminal after making the changes, repeatedly entering the system installation option (the first few attempts may still show network error messages). However, after a few tries, I was able to proceed to the license agreement step. At this point, if I return to the terminal, both `ping` and `curl` resolve correctly.

**Comment by ncheng89** [comment]
> > But the DNS still does not work, there is no problem with the gateway
> 
> Yes, I did encounter this issue. It feels like a DNS service needs to be restarted, but I don't know how to do that in recovery mode. After writing to `/etc/resolv.conf`, both `ping` and `curl` fail to resolve immediately.
> 
> What I did was close the terminal after making the changes, repeatedly entering the system installation option (the first few attempts may still show network error messages). However, after a few tries, I was able to proceed to the license agreement step. At this point, if I return to the terminal, both `ping` and `curl` resolve correctly.

It is indeed true. It is very strange. The terminal cannot resolve the domain name by dns. But it works after clicking on the installation system.
![image](https://github.com/user-attachments/assets/3d716547-b048-4ffa-a1de-dca87f8b9177)

**Comment by virkingz** [comment]
> > > 但DNS还是不行，网关没有问题
> > 
> > 
> > 是的，我确实遇到了这个问题。感觉好像需要重新启动 DNS 服务，但我不知道如何在恢复模式下执行此操作。写入后`/etc/resolv.conf`，`ping`和都`curl`无法立即解析。
> > 我所做的是在进行更改后关闭终端，反复输入系统安装选项（前几次尝试可能仍会显示网络错误消息）。但是，经过几次尝试，我能够继续进行许可协议步骤。此时，如果我返回终端，和都可以`ping`正确`curl`解析。
> 
> 确实是这样的，很奇怪，终端无法通过dns解析域名，但是点击安装系统后就可以了。 ![图像](https://private-user-images.githubusercontent.com/48044818/398882328-3d716547-b048-4ffa-a1de-dca87f8b9177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODU0ODAsIm5iZiI6MTczNTI4NTE4MCwicGF0aCI6Ii80ODA0NDgxOC8zOTg4ODIzMjgtM2Q3MTY1NDctYjA0OC00ZmZhLWExZGUtZGNhODdmOGI5MTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA3Mzk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YTk3OWM3NzljYmZjNjU4YWNlODJjM2U4YjYwNWVjN2E0Y2YwM2NkYjk1YTdlODM4MmNkMDFmMTkzZTA5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jJWpxz2I3ZJrBUPo5dCSkPhpAXbV8xFqp8eA-jI3wC4)

After you have successfully installed it, please let me know that I am currently stuck and unable to start properly
![image](https://github.com/user-attachments/assets/5c752df3-df87-4317-bfdd-278d60b843ba)

**Comment by ncheng89** [comment]
@virkingz 
After the installation is complete, I can boot into the system normally. Did you divide too many partitions into partitions? Try dividing only one hard disk partition and then install the system.

![image](https://github.com/user-attachments/assets/7f85ade5-5ab1-4178-a724-c9360b5bdbfa)

**Comment by virkingz** [comment]
> @virkingz After the installation is complete, I can boot into the system normally. Did you divide too many partitions into partitions? Try dividing only one hard disk partition and then install the system.
> 
> ![image](https://private-user-images.githubusercontent.com/48044818/398893656-7f85ade5-5ab1-4178-a724-c9360b5bdbfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODg3MTYsIm5iZiI6MTczNTI4ODQxNiwicGF0aCI6Ii80ODA0NDgxOC8zOTg4OTM2NTYtN2Y4NWFkZTUtNWFiMS00MTc4LWE3MjQtYzkzNjBiNWJkYmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4MzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZWI3YTgyM2E2OTE4MmI5YmZkZDY1OGFjM2M0YTUzY2QyZWYzMTY4MzEyOGI5NzlkYWVhZDQ2YzMxOGVkOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X17lnX7WTuVDBj3l0sEpFmhjmaaVuPqwnzS2jYU1SK8)

I followed the process：
Choose Disk Utility and then select the largest Apple Inc. VirtIO Block Media disk.
Click the Erase button to format the disk to APFS, and give it any recognizable name you like.
Close the current window and proceed the installation by clicking Reinstall macOS.
When prompted where you want to install it, select the disk you just created previously.

I don't know where I made a mistake

**Comment by ncheng89** [comment]
![image](https://github.com/user-attachments/assets/d1303db1-6dfe-4d7d-93bf-881f104ef98f)
What is the name of your disk partition? What will happen if you click the corresponding disk with the mouse?

**Comment by virkingz** [comment]
> ![image](https://private-user-images.githubusercontent.com/48044818/398895309-d1303db1-6dfe-4d7d-93bf-881f104ef98f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODkxNjUsIm5iZiI6MTczNTI4ODg2NSwicGF0aCI6Ii80ODA0NDgxOC8zOTg4OTUzMDktZDEzMDNkYjEtNmRmZS00ZDdkLTkzYmYtODgxZjEwNGVmOThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4NDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NGUzODczNjIxYzI4MDY2MDUwMDhhMjNiNjdmMGNkNTkyYzE4M2Q4OGYxOGY4ZDYzNjgzMDU5NjFiMjcxNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ic0CmntyUskdylhLugUTzCQa9s1KzaWn4_27n8lJplg) What is the name of your disk partition? What will happen if you click the corresponding disk with the mouse?

It will prompt a system error and keep restarting

**Comment by ncheng89** [comment]
Did you use the -v parameter to persist the disk? If you did, try deleting everything and then starting over.

**Comment by virkingz** [comment]
> 您是否使用了 -v 参数来持久保存磁盘？如果使用了，请尝试删除所有内容，然后重新开始。

OK, I'll give it a try

**Comment by puteulanus** [comment]
I attempted to install macOS 14 in a fresh container and encountered the same issue. This is a screenshot of the logs obtained after modifying the boot args. Since I couldn't prevent the system from rebooting upon a crash and don't understand why the VNC resolution changes during the crash, it's been very difficult to capture the complete logs.

![QQ_1735310616261](https://github.com/user-attachments/assets/254b84c3-02dd-42be-91f8-f948e0739c6e)

PS:
From searching the error shown in the screenshot, I found this issue: https://github.com/paolo-projects/auto-unlocker/issues/86#issuecomment-1320186820. The problem seems to be related to the lack of AVX2 support in the CPU. The CPU on my machine is N5105, which does not support AVX/AVX2 instructions (the result of `cat /proc/cpuinfo | grep avx` is empty).

**Comment by puteulanus** [comment]
Also crash after macOS 13 installed:

![QQ_1735358540949](https://github.com/user-attachments/assets/115c7a88-0ab7-4a22-a13d-ef71eba50dcf)

![QQ_1735358558394](https://github.com/user-attachments/assets/d663597e-2ff7-40d6-92ab-e59c18bebb0a)

**Comment by virkingz** [comment]
You're right, it can start normally when I change the device

**Comment by virkingz** [comment]
> Also crash after macOS 13 installed:
> 
> ![QQ_1735358540949](https://private-user-images.githubusercontent.com/4849177/399037472-115c7a88-0ab7-4a22-a13d-ef71eba50dcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1Mjc5ODMsIm5iZiI6MTczNTUyNzY4MywicGF0aCI6Ii80ODQ5MTc3LzM5OTAzNzQ3Mi0xMTVjN2E4OC0wYWI3LTRhMjItYTEzZC1lZjcxZWJhNTBkY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMDMwMTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgxZjIxMGI4YjdhNjc2Y2VjZWNkNDBiNzAwODJkZWNmMGJmM2Y5YTFjOTAwMTY2MmY2MmJiOGE5YTU0MzYyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iFytlnXm_IwJ2TWpWM954ZxqSPCEtb4570FG8S-HPjY)
> 
> ![QQ_1735358558394](https://private-user-images.githubusercontent.com/4849177/399037479-d663597e-2ff7-40d6-92ab-e59c18bebb0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1Mjc5ODMsIm5iZiI6MTczNTUyNzY4MywicGF0aCI6Ii80ODQ5MTc3LzM5OTAzNzQ3OS1kNjYzNTk3ZS0yZmY3LTQwZDYtOTJhYi1lNTljMThiZWJiMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMDMwMTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg1ZjkzN2QzZjVhOWIxNDM3ZDdhODVhNWU2YTNhOGQ1YzQyMWJjZDE5YWI1ZGY5NDEzYmEzNTZkMDhiMDhiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.USq36LwKJaYT_afH06GJ1j5peU2H2qPLJIJeVB86iXo)

You're right, it can start normally when I change the device
