### ISSUE TITLE
[Feature]: Change screen resolution

### ISSUE THREAD

**Issue by seitenca** [dockur/macos#23]
### Is your proposal related to a problem?

Its not possible to change the resolution.

### Describe the solution you'd like.

Solution 1:
Generate the OpenCore boot drive on demand. We might also need to generate new OVMF variables, as mentioned [here](https://github.com/kholia/OSX-KVM/blob/master/notes.md#change-resolution-in-opencore). They mention that the macOS VM's resolution can be changed easily via the "Settings -> Displays" option, but in my case, it is not possible or I have not figured it out yet.

Solution 2:
Add 3 or 4 resolution options (1080p, 720p, 4K, etc.) to the image.

### Describe alternatives you've considered.

I have tried to generate the OpenCore boot drive as mentioned [here](https://github.com/kholia/OSX-KVM/blob/master/OpenCore/README.md#notes) but have failed to do so. I'm also now looking on how to generate new OVMF variables.

**Comment by GeekWorkCode** [comment]
> 是的，我认为需要在文件中进行更改`config.plist`。但目前我们不会在每次启动时生成此映像，而是仅在构建 Dockerfile 时生成一次。
> 
> 因此，解决方案是在每次容器启动时动态地重新生成 OpenCore 映像。（或者最好仅当用户更改值时才生成`BOOT_MODE`，否则跳过）。
> 
> 但我真的怀疑这是否值得付出努力。高于 1080p 的分辨率对于通过 VNC 或没有 GPU 加速进行渲染来说会太慢。而低于 1080p 的分辨率对大多数人来说并不真正有趣。所以就我个人而言，我认为将其固定在 1080p 是没有问题的。你有什么特别的理由想要改变它吗？

I want to use macOS for CI/CD-related purposes (sign into Xcode, Transporter),The machine configuration is not high, and the resolution needs to be lowered.  I'm only interested in using the command line

**Comment by GeekWorkCode** [comment]
> Yes I think it needs to be changed in the `config.plist` file. But currently we generate this image not during every boot, but only once while building the Dockerfile.
> 
> So the solution would be to re-generate the OpenCore image dynamicly every time the container starts. (Or optimally only when the user changed the `BOOT_MODE` value, and skipped otherwise).
> 
> But I really doubt it is worth the effort. Resolutions greater than 1080p will be much too slow to render via VNC or without GPU acceleration. And resolutions much lower than 1080p are not really interesting for most people. So for me personally I think its no problem to keep it fixed at 1080p. Do you have any special reason for wanting to change it?

I want to use macOS for CI/CD-related purposes (sign into Xcode, Transporter),The machine configuration is not high, and the resolution needs to be lowered. I'm only interested in using the command line

**Comment by dojoca** [comment]
Just giving this a nudge... and asking a question. 

I'm a bit of a novice user here, but I was wondering if it is possible to change the resolution (or allow more resolutions)? I tried to create a custom config.plist file including another resolution, but I wasn't sure how to get this file to be used by the docker container?

**Comment by nizioleque** [comment]
Another reason - I want to use it on a 16:10 (1920x1200) screen without black bars on top and bottom. Any update on that feature?

**Comment by KaivnD** [comment]
> I'm only interested in using the command line

@GeekWorkCode you should try this https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server
